// Types for action creators of saga requests
export const REQUEST_HELLO_SAGA = 'SAGA/REQUEST_HELLO_SAGA';
export const REQUEST_BRANDS = 'SAGA/REQUEST_BRANDS';
export const REQUEST_MODELS = 'SAGA/REQUEST_MODELS';
export const REQUEST_NEW_VEHICLES = 'SAGA/REQUEST_NEW_VEHICLES';
export const REQUEST_NEW_VEHICLE = 'SAGA/REQUEST_NEW_VEHICLE';
export const REQUEST_TRADEIN_VEHICLES = 'SAGA/REQUEST_TRADEIN_VEHICLES';
export const REQUEST_TRADEIN_VEHICLE = 'SAGA/REQUEST_TRADEIN_VEHICLE';
export const REQUEST_ALL_NEW_VEHICLES = 'SAGA/REQUEST_ALL_NEW_VEHICLES';

// Types for action creators of filters
export const CHANGE_FILTER_STATE = 'CHANGE_FILTER_STATE';
export const ADD_FILTER_ITEMS = 'ADD_FILTER_ITEMS';
export const ADD_SELECT_ITEM_ID_TO_SELECTED = 'ADD_SELECT_ITEM_ID_TO_SELECTED';
export const ADD_FILTERDISABLED_ITEMS = 'ADD_FILTERDISABLED_ITEMS';
export const ADD_FILTER_PRICE = 'ADD_FILTER_PRICE';

// Types for action creators of loaders
export const CHANGE_MODELS_LOADER = 'CHANGE_MODELS_LOADER';
export const CHANGE_VEHICLES_LOADER = 'CHANGE_VEHICLES_LOADER';
export const CHANGE_TRADEIN_VEHICLES_LOADER = 'CHANGE_TRADEIN_VEHICLES_LOADER';